version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_attendance11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: attendance_db
    ports:
      - "5452:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - attendance-net

  backend:
    build:
      context: ./Backend
    container_name: attendance-backend11
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin834
      DB_NAME: attendance_db
      PORT: 3006
    ports:
      - "3052:3052"
    networks:
      - attendance-net

  employee-attendance:
    build:
      context: ./Employee-attendance
    container_name: employee-attendance11
    depends_on:
      - backend
    ports:
      - "8053:80"
    networks:
      - attendance-net

  hr-attendance:
    build:
      context: ./HR-attendance
    container_name: hr-attendance12
    depends_on:
      - backend
    ports:
      - "8054:80"
    networks:
      - attendance-net
volumes:
  postgres_data:

networks:
  attendance-net:

